MODEL:
  CLASSIFIER_ON: True
  CLASSIFIER:
    ENCODING_TYPE: "MesoInception4"
    DECODING_TYPE: "TwoBranch"
    NUM_CLASS: 2
    NUM_DOMAIN: 2
    DOMAIN_LAMBDA: 0.1
  WEIGHT: "./outputs/baseline_deep_fake_detection_mesonet_inc4/model_final.pth"

DATASETS:
  TRAIN: ("deep_fake_merged_train_d500_c1500",)
  TEST: ("deep_fake_detection_test", "deep_fake_celeb_test")

DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False

SOLVER:
  BASE_LR: 0.02
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (4000, 8000)
  MAX_ITER: 12000
  IMS_PER_BATCH: 128
  TEST_PERIOD: 2000
  RESUME: False

OUTPUT_DIR: "./outputs/two_branch_merged_mesonet_inc4"

INPUT:
  MIN_SIZE_TRAIN: (256, )
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0
  VERTICAL_FLIP_PROB_TRAIN: 0.0
TEST:
  IMS_PER_BATCH: 128
  VIS: True
